# Generated by Django 4.2.23 on 2025-11-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('unidade_medida', models.CharField(max_length=20)),
            ],
        ),
    ]
