# Generated by Django 4.2.23 on 2025-11-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('AL', 'Alimentos'), ('HG', 'Higiene'), ('LM', 'Limpeza'), ('VD', 'Vestuário'), ('OT', 'Outros')], default='OT', max_length=2),
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.item')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.item')),
            ],
        ),
    ]
