# Generated by Django 5.2.8 on 2025-11-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Doador',
                'verbose_name_plural': 'Doadores',
            },
        ),
        migrations.CreateModel(
            name='EntidadeBeneficiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('num_beneficiados', models.PositiveIntegerField(default=0, verbose_name='Pessoas Atendidas')),
            ],
            options={
                'verbose_name': 'Entidade Beneficiada',
                'verbose_name_plural': 'Entidades Beneficiadas',
            },
        ),
    ]
