# Generated by Django 5.2.8 on 2025-11-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadeBeneficiada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='ONG/Família')),
                ('responsavel', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='BAIXA', max_length=5)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
