# Generated by Django 5.2.5 on 2025-11-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidade_beneficiada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidadebeneficiada',
            name='num_membros',
            field=models.PositiveIntegerField(default=1, help_text='Número de indivíduos que serão beneficiados pela doação.', verbose_name='Pessoas Atendidas / Membros da Família'),
        ),
    ]
