# Generated by Django 4.2.11 on 2025-11-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidade_beneficiada', '0002_entidadebeneficiada_num_membros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadebeneficiada',
            options={'verbose_name': 'Entidade Beneficiada', 'verbose_name_plural': 'Entidades Beneficiadas'},
        ),
    ]
