# Generated by Django 4.2.23 on 2025-11-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_coleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontocoleta',
            options={},
        ),
        migrations.AddField(
            model_name='pontocoleta',
            name='coletado',
            field=models.BooleanField(default=False),
        ),
    ]
