# Generated by Django 4.2.23 on 2025-11-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('unidade_medida', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('AL', 'Alimentos'), ('HG', 'Higiene'), ('LM', 'Limpeza'), ('VD', 'Vestuário'), ('OT', 'Outros')], max_length=2)),
                ('doador', models.CharField(max_length=100)),
                ('data_doacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
