# Generated by Django 4.2.23 on 2025-11-29 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_coleta', '0001_initial'),
        ('doacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='coletada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doacao',
            name='ponto_coleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doacoes', to='ponto_coleta.pontocoleta'),
        ),
    ]
