# Generated by Django 4.2.23 on 2025-11-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponto_coleta', '0001_initial'),
        ('doacao', '0002_doacao_coletada_doacao_ponto_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='ponto_coleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ponto_coleta.pontocoleta'),
        ),
    ]
