# Generated by Django 4.2.11 on 2025-12-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0003_doador_cnpj_doador_cpf_doador_usuario'),
        ('doacao', '0003_alter_doacao_ponto_coleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doador.doador'),
        ),
    ]
