# Generated by Django 6.0 on 2025-12-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0004_alter_doacao_doador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='doador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
