# Generated by Django 4.2.11 on 2025-11-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='tipo',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de Doador'),
        ),
        migrations.AlterField(
            model_name='doador',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome/Razão Social'),
        ),
    ]
